export default [
  {
    name: "You Don't Know Jack - 2015",
    pack: "The Jackbox Party Pack",
    minPlayers: 1,
    maxPlayers: 4,
    url: "https://jackboxgames.com/ydkj-2015",
    description:
      "The comedy trivia sensation with hundreds of all-new questions.",
    pack_url: "https://www.jackboxgames.com/party-pack/",
    duration: "20 Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Lie Swatter",
    pack: "The Jackbox Party Pack",
    minPlayers: 1,
    maxPlayers: 100,
    url: "https://jackboxgames.com/lie-swatter",
    description: "The wacky-fact-filled Lie Swatter.",
    pack_url: "https://www.jackboxgames.com/party-pack/",
    duration: "20 Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: false,

  },
  {
    name: "Fibbage XL",
    pack: "The Jackbox Party Pack",
    minPlayers: 2,
    maxPlayers: 8,
    url: "https://jackboxgames.com/fibbage-xl",
    description:
      "The hilarious bluffing game with 50% more questions added to the original hit.",
    pack_url: "https://www.jackboxgames.com/party-pack/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Word Spud",
    pack: "The Jackbox Party Pack",
    minPlayers: 2,
    maxPlayers: 8,
    url: "https://jackboxgames.com/word-spud",
    description: "The racy-as-you-want-to-be fill-in-the-blank word game.",
    pack_url: "https://www.jackboxgames.com/party-pack/",
    duration: "Unlimited",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: false,

  },
  {
    name: "Drawful",
    pack: "The Jackbox Party Pack",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/drawful",
    description:
      "The bizarre drawing game where you draw right there on your phone or tablet.",
    pack_url: "https://www.jackboxgames.com/party-pack/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Bomb Corp.",
    pack: "The Jackbox Party Pack 2",
    minPlayers: 1,
    maxPlayers: 4,
    url: "https://jackboxgames.com/bomb-corp",
    description:
      "The bomb-defusing nailbiter of a party game! As interns at Bomb Corp., you must defuse random bombs in the office in order to keep your jobs. You’ll probably die, but it’ll be good work experience!",
    pack_url: "https://www.jackboxgames.com/party-pack-two/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Fibbage 2",
    pack: "The Jackbox Party Pack 2",
    minPlayers: 2,
    maxPlayers: 8,
    url: "https://jackboxgames.com/fibbage-two",
    description:
      "The runaway hit bluffing game with over 500 brand-new questions, more than 2x the original! Plus new features, like the deFIBrillator!",
    pack_url: "https://www.jackboxgames.com/party-pack-two/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,

  },
  {
    name: "Bidiots",
    pack: "The Jackbox Party Pack 2",
    minPlayers: 3,
    maxPlayers: 6,
    url: "https://jackboxgames.com/bidiots",
    description:
      "The absurd art auction game where you draw right there on your phone or tablet. Outbid your opponents for weird art pieces – drawn by players themselves – and win this strangely competitive auction game! Don’t be a bidiot!",
    pack_url: "https://www.jackboxgames.com/party-pack-two/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,

  },
  {
    name: "Earwax",
    pack: "The Jackbox Party Pack 2",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/earwax",
    description:
      "The hear-larious sound-effects game that will leave you up to your ears in laughter! Cow moo? Huge explosion? Or tiny fart? Which to choose?",
    pack_url: "https://www.jackboxgames.com/party-pack-two/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Quiplash XL",
    pack: "The Jackbox Party Pack 2",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/quiplash-xl",
    description:
      "The say-anything, gut-busting Quiplash XL, which includes everything in Quiplash, Quip Pack 1, AND over 100 brand-new prompts!",
    pack_url: "https://www.jackboxgames.com/party-pack-two/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Trivia Murder Party",
    pack: "The Jackbox Party Pack 3",
    minPlayers: 1,
    maxPlayers: 8,
    url: "https://jackboxgames.com/trivia-murder-party",
    description:
      "A deadly quiz show where you match wits with a trivia-obsessed killer.",
    pack_url: "https://www.jackboxgames.com/party-pack-three/",
    duration: "15-20 Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: true,
  },
  {
    name: "Guesspionage",
    pack: "The Jackbox Party Pack 3",
    minPlayers: 2,
    maxPlayers: 8,
    url: "https://jackboxgames.com/guesspionage",
    description: "The brain-battering data-mining guessing game.",
    pack_url: "https://www.jackboxgames.com/party-pack-three/",
    duration: "10-15 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Fakin' It",
    pack: "The Jackbox Party Pack 3",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/fakin-it",
    description:
      "One of your friends has something to hide in this sneaky game for tricksters.",
    pack_url: "https://www.jackboxgames.com/party-pack-three/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: false,
  },
  {
    name: "Quiplash 2",
    pack: "The Jackbox Party Pack 3",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/quiplash-two",
    description:
      "The say-anything sequel. Play all new questions or make your own!",
    pack_url: "https://www.jackboxgames.com/party-pack-three/",
    duration: "15 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Tee K.O.",
    pack: "The Jackbox Party Pack 3",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/tee-ko",
    description:
      "The t-shirt slugfest where you battle your custom t-shirts to the death!",
    pack_url: "https://www.jackboxgames.com/party-pack-three/",
    duration: "30 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Fibbage 3",
    pack: "The Jackbox Party Pack 4",
    minPlayers: 2,
    maxPlayers: 8,
    url: "https://jackboxgames.com/fibbage-three",
    description:
      "The blanking fun sequel with all-new question types and the game mode Fibbage: Enough About You where you guess the weird facts about your friends.",
    pack_url: "https://www.jackboxgames.com/party-pack-four/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Monster Seeking Monster",
    pack: "The Jackbox Party Pack 4",
    minPlayers: 3,
    maxPlayers: 7,
    url: "https://jackboxgames.com/monster-seeking-monster",
    description:
      "The spooky date-a-thon where you message and date fellow monsters with special powers.",
    pack_url: "https://www.jackboxgames.com/party-pack-four/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Civic Doodle",
    pack: "The Jackbox Party Pack 4",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/civic-doodle",
    description:
      "The one-up art game where you compete to improve the town murals. Play using your phones, tablets or computers. No extra controllers needed! Plus EVEN MORE features just for streamers!",
    pack_url: "https://www.jackboxgames.com/party-pack-four/",
    duration: "20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Survive the Internet",
    pack: "The Jackbox Party Pack 4",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/survive-the-internet",
    description:
      "The web-based frame game where you twist your friends’ “online” comments in hilarious ways.",
    pack_url: "https://www.jackboxgames.com/party-pack-four/",
    duration: "20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Bracketeering",
    pack: "The Jackbox Party Pack 4",
    minPlayers: 3,
    maxPlayers: 16,
    url: "https://jackboxgames.com/bracketeering",
    description:
      "The deranged debate match where you place smart bets on stupid arguments.",
    pack_url: "https://www.jackboxgames.com/party-pack-four/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "You Don't Know Jack - Full Stream",
    pack: "The Jackbox Party Pack 5",
    minPlayers: 1,
    maxPlayers: 8,
    url: "https://jackboxgames.com/ydkj-full-stream",
    description:
      "The pop-culture trivia mash-up YOU DON’T KNOW JACK: Full Stream. The classic returns, full of wild new surprises.",
    pack_url: "https://www.jackboxgames.com/party-pack-five/",
    duration: "15-20 Minutes",
    familyFriendlySetting: false,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Split The Room",
    pack: "The Jackbox Party Pack 5",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/split-the-room",
    description:
      "The what-if game Split the Room. Create strange and divisive hypothetical situations.",
    pack_url: "https://www.jackboxgames.com/party-pack-five/",
    duration: "15 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Mad Verse City",
    pack: "The Jackbox Party Pack 5",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/mad-verse-city",
    description:
      "The lyric-writing game Mad Verse City. Channel your inner MC as a rap battling robot.",
    pack_url: "https://www.jackboxgames.com/party-pack-five/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Patently Stupid",
    pack: "The Jackbox Party Pack 5",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/patently-stupid",
    description:
      "The competitive drawing game Patently Stupid. Create odd inventions to solve bizarre problems.",
    pack_url: "https://www.jackboxgames.com/party-pack-five/",
    duration: "20 Minutes",
    familyFriendlySetting: false,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Zeeple Dome",
    pack: "The Jackbox Party Pack 5",
    minPlayers: 1,
    maxPlayers: 6,
    url: "https://jackboxgames.com/zeeple-dome",
    description:
      "The deadliest game show in the Crab Nebula, Zeeple Dome! Fling yourself at bloodthirsty aliens to win millions of Zubabucks!",
    pack_url: "https://www.jackboxgames.com/party-pack-five/",
    duration: "10+ Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Trivia Murder Party 2",
    pack: "The Jackbox Party Pack 6",
    minPlayers: 1,
    maxPlayers: 8,
    url: "https://jackboxgames.com/trivia-murder-party-two/",
    description:
      "The popular trivia deathmatch Trivia Murder Party 2. Try to survive the bizarre new minigames.",
    pack_url: "https://www.jackboxgames.com/party-pack-six/",
    duration: "15-25 Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: true,
  },
  {
    name: "Role Models",
    pack: "The Jackbox Party Pack 6",
    minPlayers: 3,
    maxPlayers: 6,
    url: "https://jackboxgames.com/role-models/",
    description:
      "The offbeat personality test Role Models. Find out who you really are. (Or at least what your friends think of you.)",
    pack_url: "https://www.jackboxgames.com/party-pack-six/",
    duration: "15 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Joke Boat",
    pack: "The Jackbox Party Pack 6",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/joke-boat/",
    description:
      "The comedy contest Joke Boat. Craft one-liners for a cruise ship talent show.",
    pack_url: "https://www.jackboxgames.com/party-pack-six/",
    duration: "15-25 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Dictionarium",
    pack: "The Jackbox Party Pack 6",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/dictionarium/",
    description:
      "The weird word circus Dictionarium. May the funniest definition win.",
    pack_url: "https://www.jackboxgames.com/party-pack-six/",
    duration: "10 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Push The Button",
    pack: "The Jackbox Party Pack 6",
    minPlayers: 4,
    maxPlayers: 10,
    url: "https://jackboxgames.com/push-the-button/",
    description:
      "The hidden identity game Push The Button. Can you discover the aliens in time? ",
    pack_url: "https://www.jackboxgames.com/party-pack-six/",
    duration: "Varies by player count",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: false,
  },
  {
    name: "Drawful 2",
    pack: "Standalone Title",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/drawful-two/",
    description:
      "Your phones or tablets are your controllers! The game of terrible drawings and hilariously wrong answers.",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Fibbage",
    pack: "Standalone Title",
    minPlayers: 2,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/fibbage/",
    description:
      "Fibbage is the lying, bluffing, fib-till-you-win trivia party game from the makers of YOU DON’T KNOW JACK! Fool your friends with your lies, avoid theirs, and find the (usually outrageous) truth. And get this: your phone or tablet is your controller!",
    duration: "15-20 Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Quiplash",
    pack: "Standalone Title",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/quiplash/",
    description: "Quiplash is the gut-busting battle of wits and wittiness!",
    duration: "15 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "You Don't Know Jack - Classic Bundle",
    pack: "Standalone Title",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/ydkj-classic-bundle/",
    description:
      "Since 1995, Jackbox Games (formerly Jellyvision) has been making YOU DON’T KNOW JACK, the hit comedy trivia series where high culture and pop culture collide. And we refuse to stop until every human being has played it.",
    duration: "25 Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Quiplash 2 InterLASHional",
    pack: "Standalone Title",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/quiplash-two-interlashional/",
    description: "The “say anything” party game is going international! All the hilarious content from Quiplash 2, now in French, Italian, German, and Spanish! With 100 NEW prompts in each language! (And you can still play in boring old English.) Get this QUINTILINGUAL Quiplash now, and take your next party global!",
    duration: "15 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  }
];
