const games = [
  {
    name: "You Don't Know Jack - 2015",
    pack: "The Jackbox Party Pack",
    image: "ydkj_2015.jpg",
    minPlayers: 1,
    maxPlayers: 4,
    url: "https://jackboxgames.com/ydkj-2015",
    description:
      "The comedy trivia sensation with hundreds of all-new questions.",
    pack_url: "https://www.jackboxgames.com/party-pack/",
    duration: "20 Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Lie Swatter",
    pack: "The Jackbox Party Pack",
    image: "lie_swatter.jpg",
    minPlayers: 1,
    maxPlayers: 100,
    url: "https://jackboxgames.com/lie-swatter",
    description: "The wacky-fact-filled Lie Swatter.",
    pack_url: "https://www.jackboxgames.com/party-pack/",
    duration: "20 Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Fibbage XL",
    pack: "The Jackbox Party Pack",
    image: "fibbage_xl.jpg",
    minPlayers: 2,
    maxPlayers: 8,
    url: "https://jackboxgames.com/fibbage-xl",
    description:
      "The hilarious bluffing game with 50% more questions added to the original hit.",
    pack_url: "https://www.jackboxgames.com/party-pack/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Word Spud",
    pack: "The Jackbox Party Pack",
    image: "word_spud.jpg",
    minPlayers: 2,
    maxPlayers: 8,
    url: "https://jackboxgames.com/word-spud",
    description: "The racy-as-you-want-to-be fill-in-the-blank word game.",
    pack_url: "https://www.jackboxgames.com/party-pack/",
    duration: "Unlimited",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Drawful",
    pack: "The Jackbox Party Pack",
    image: "drawful.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/drawful",
    description:
      "The bizarre drawing game where you draw right there on your phone or tablet.",
    pack_url: "https://www.jackboxgames.com/party-pack/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Bomb Corp.",
    pack: "The Jackbox Party Pack 2",
    image: "bomb_corp.jpg",
    minPlayers: 1,
    maxPlayers: 4,
    url: "https://jackboxgames.com/bomb-corp",
    description:
      "The bomb-defusing nailbiter of a party game! As interns at Bomb Corp., you must defuse random bombs in the office in order to keep your jobs. You’ll probably die, but it’ll be good work experience!",
    pack_url: "https://www.jackboxgames.com/party-pack-two/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Fibbage 2",
    pack: "The Jackbox Party Pack 2",
    image: "fibbage_2.jpg",
    minPlayers: 2,
    maxPlayers: 8,
    url: "https://jackboxgames.com/fibbage-two",
    description:
      "The runaway hit bluffing game with over 500 brand-new questions, more than 2x the original! Plus new features, like the deFIBrillator!",
    pack_url: "https://www.jackboxgames.com/party-pack-two/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Bidiots",
    pack: "The Jackbox Party Pack 2",
    image: "bidiots.jpg",
    minPlayers: 3,
    maxPlayers: 6,
    url: "https://jackboxgames.com/bidiots",
    description:
      "The absurd art auction game where you draw right there on your phone or tablet. Outbid your opponents for weird art pieces – drawn by players themselves – and win this strangely competitive auction game! Don’t be a bidiot!",
    pack_url: "https://www.jackboxgames.com/party-pack-two/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Earwax",
    pack: "The Jackbox Party Pack 2",
    image: "earwax.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/earwax",
    description:
      "The hear-larious sound-effects game that will leave you up to your ears in laughter! Cow moo? Huge explosion? Or tiny fart? Which to choose?",
    pack_url: "https://www.jackboxgames.com/party-pack-two/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Quiplash XL",
    pack: "The Jackbox Party Pack 2",
    image: "quiplash_xl.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/quiplash-xl",
    description:
      "The say-anything, gut-busting Quiplash XL, which includes everything in Quiplash, Quip Pack 1, AND over 100 brand-new prompts!",
    pack_url: "https://www.jackboxgames.com/party-pack-two/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Trivia Murder Party",
    pack: "The Jackbox Party Pack 3",
    image: "trivia_murder_party.jpg",
    minPlayers: 1,
    maxPlayers: 8,
    url: "https://jackboxgames.com/trivia-murder-party",
    description:
      "A deadly quiz show where you match wits with a trivia-obsessed killer.",
    pack_url: "https://www.jackboxgames.com/party-pack-three/",
    duration: "15-20 Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: true,
  },
  {
    name: "Guesspionage",
    pack: "The Jackbox Party Pack 3",
    image: "guesspionage.jpg",
    minPlayers: 2,
    maxPlayers: 8,
    url: "https://jackboxgames.com/guesspionage",
    description: "The brain-battering data-mining guessing game.",
    pack_url: "https://www.jackboxgames.com/party-pack-three/",
    duration: "10-15 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Fakin' It",
    pack: "The Jackbox Party Pack 3",
    image: "fakin_it.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/fakin-it",
    description:
      "One of your friends has something to hide in this sneaky game for tricksters.",
    pack_url: "https://www.jackboxgames.com/party-pack-three/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: false,
  },
  {
    name: "Quiplash 2",
    pack: "The Jackbox Party Pack 3",
    image: "quiplash_2.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/quiplash-two",
    description:
      "The say-anything sequel. Play all new questions or make your own!",
    pack_url: "https://www.jackboxgames.com/party-pack-three/",
    duration: "15 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Tee K.O.",
    pack: "The Jackbox Party Pack 3",
    image: "tee_ko.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/tee-ko",
    description:
      "The t-shirt slugfest where you battle your custom t-shirts to the death!",
    pack_url: "https://www.jackboxgames.com/party-pack-three/",
    duration: "30 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Fibbage 3",
    pack: "The Jackbox Party Pack 4",
    image: "fibbage_3.png",
    minPlayers: 2,
    maxPlayers: 8,
    url: "https://jackboxgames.com/fibbage-three",
    description:
      "The blanking fun sequel with all-new question types and the game mode Fibbage: Enough About You where you guess the weird facts about your friends.",
    pack_url: "https://www.jackboxgames.com/party-pack-four/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Monster Seeking Monster",
    pack: "The Jackbox Party Pack 4",
    image: "monster_seeking_monster.jpg",
    minPlayers: 3,
    maxPlayers: 7,
    url: "https://jackboxgames.com/monster-seeking-monster",
    description:
      "The spooky date-a-thon where you message and date fellow monsters with special powers.",
    pack_url: "https://www.jackboxgames.com/party-pack-four/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Civic Doodle",
    pack: "The Jackbox Party Pack 4",
    image: "civic_doodle.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/civic-doodle",
    description:
      "The one-up art game where you compete to improve the town murals. Play using your phones, tablets or computers. No extra controllers needed! Plus EVEN MORE features just for streamers!",
    pack_url: "https://www.jackboxgames.com/party-pack-four/",
    duration: "20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Survive the Internet",
    pack: "The Jackbox Party Pack 4",
    image: "survive_the_internet.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/survive-the-internet",
    description:
      "The web-based frame game where you twist your friends’ “online” comments in hilarious ways.",
    pack_url: "https://www.jackboxgames.com/party-pack-four/",
    duration: "20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Bracketeering",
    pack: "The Jackbox Party Pack 4",
    image: "bracketeering.jpg",
    minPlayers: 3,
    maxPlayers: 16,
    url: "https://jackboxgames.com/bracketeering",
    description:
      "The deranged debate match where you place smart bets on stupid arguments.",
    pack_url: "https://www.jackboxgames.com/party-pack-four/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "You Don't Know Jack - Full Stream",
    pack: "The Jackbox Party Pack 5",
    image: "full_stream.png",
    minPlayers: 1,
    maxPlayers: 8,
    url: "https://jackboxgames.com/ydkj-full-stream",
    description:
      "The pop-culture trivia mash-up YOU DON’T KNOW JACK: Full Stream. The classic returns, full of wild new surprises.",
    pack_url: "https://www.jackboxgames.com/party-pack-five/",
    duration: "15-20 Minutes",
    familyFriendlySetting: false,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Split The Room",
    pack: "The Jackbox Party Pack 5",
    image: "split_the_room.png",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/split-the-room",
    description:
      "The what-if game Split the Room. Create strange and divisive hypothetical situations.",
    pack_url: "https://www.jackboxgames.com/party-pack-five/",
    duration: "15 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Mad Verse City",
    pack: "The Jackbox Party Pack 5",
    image: "mad_verse_city.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/mad-verse-city",
    description:
      "The lyric-writing game Mad Verse City. Channel your inner MC as a rap battling robot.",
    pack_url: "https://www.jackboxgames.com/party-pack-five/",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Patently Stupid",
    pack: "The Jackbox Party Pack 5",
    image: "patently_stupid.png",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/patently-stupid",
    description:
      "The competitive drawing game Patently Stupid. Create odd inventions to solve bizarre problems.",
    pack_url: "https://www.jackboxgames.com/party-pack-five/",
    duration: "20 Minutes",
    familyFriendlySetting: false,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Zeeple Dome",
    pack: "The Jackbox Party Pack 5",
    image: "zeeple_dome.jpg",
    minPlayers: 1,
    maxPlayers: 6,
    url: "https://jackboxgames.com/zeeple-dome",
    description:
      "The deadliest game show in the Crab Nebula, Zeeple Dome! Fling yourself at bloodthirsty aliens to win millions of Zubabucks!",
    pack_url: "https://www.jackboxgames.com/party-pack-five/",
    duration: "10+ Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Trivia Murder Party 2",
    pack: "The Jackbox Party Pack 6",
    image: "trivia_murder_party_2.jpg",
    minPlayers: 1,
    maxPlayers: 8,
    url: "https://jackboxgames.com/trivia-murder-party-two/",
    description:
      "The popular trivia deathmatch Trivia Murder Party 2. Try to survive the bizarre new minigames.",
    pack_url: "https://www.jackboxgames.com/party-pack-six/",
    duration: "15-25 Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: true,
  },
  {
    name: "Role Models",
    pack: "The Jackbox Party Pack 6",
    image: "role_models.jpg",
    minPlayers: 3,
    maxPlayers: 6,
    url: "https://jackboxgames.com/role-models/",
    description:
      "The offbeat personality test Role Models. Find out who you really are. (Or at least what your friends think of you.)",
    pack_url: "https://www.jackboxgames.com/party-pack-six/",
    duration: "15 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Joke Boat",
    pack: "The Jackbox Party Pack 6",
    image: "joke_boat.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/joke-boat/",
    description:
      "The comedy contest Joke Boat. Craft one-liners for a cruise ship talent show.",
    pack_url: "https://www.jackboxgames.com/party-pack-six/",
    duration: "15-25 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Dictionarium",
    pack: "The Jackbox Party Pack 6",
    image: "dictionarium.png",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/dictionarium/",
    description:
      "The weird word circus Dictionarium. May the funniest definition win.",
    pack_url: "https://www.jackboxgames.com/party-pack-six/",
    duration: "10 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Push The Button",
    pack: "The Jackbox Party Pack 6",
    image: "push_the_button.jpg",
    minPlayers: 4,
    maxPlayers: 10,
    url: "https://jackboxgames.com/push-the-button/",
    description:
      "The hidden identity game Push The Button. Can you discover the aliens in time?",
    pack_url: "https://www.jackboxgames.com/party-pack-six/",
    duration: "Varies by player count",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: false,
  },
  {
    name: "Quiplash 3",
    pack: "The Jackbox Party Pack 7",
    image: "quiplash_3.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/quiplash-three/",
    description:
      "The say-anything threequel Quiplash 3 (3-8 players). It’s a head-to-head battle of the wits as you give hilarious responses to quirky prompts while everyone else votes for their favorite!",
    pack_url: "https://www.jackboxgames.com/party-pack-seven/",
    duration: "~15 minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "The Devils and the Details",
    pack: "The Jackbox Party Pack 7",
    image: "the_devils_and_the_details.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/the-devils-and-the-details/",
    description:
      "The collaborative chaos game The Devils and the Details (3-8 players). You’re a family of devils working together to survive in suburbia. Can you handle the daily torture of human life?",
    pack_url: "https://www.jackboxgames.com/party-pack-seven/",
    duration: "~15 minutes",
    familyFriendlySetting: true,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Champ’d Up",
    pack: "The Jackbox Party Pack 7",
    image: "champd_up.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/champd-up/",
    description:
      "The drawing fighting game Champ’d Up (3-8 players). Create absurd characters that will battle over unusual titles. Can you take down the heavy favorite?",
    pack_url: "https://www.jackboxgames.com/party-pack-seven/",
    duration: "~20 minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Talking Points",
    pack: "The Jackbox Party Pack 7",
    image: "talking_points.png",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/talking-points/",
    description:
      "The on-the-spot public-speaking game Talking Points (3-8 players). Give a speech responding to picture slides you’ve never seen before or be the Assistant and approve pictures as fast as you can. Just keep talking whether it makes sense or not.",
    pack_url: "https://www.jackboxgames.com/party-pack-seven/",
    duration: "20-40 minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Blather ‘Round",
    pack: "The Jackbox Party Pack 7",
    image: "blather_round.jpg",
    minPlayers: 2,
    maxPlayers: 6,
    url: "https://www.jackboxgames.com/blather-round/",
    description:
      "The pop culture guessing game Blather Round (2-6 players). Describe your secret prompt with a very limited vocabulary and hope that someone can figure it out in time. It’s a “GOOD” “FUN TIME” “EXPERIENCE.”",
    pack_url: "https://www.jackboxgames.com/party-pack-seven/",
    duration: "15-30 minutes",
    familyFriendlySetting: true,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Drawful Animate",
    pack: "The Jackbox Party Pack 8",
    image: "drawful_animate.jpg",
    minPlayers: 3,
    maxPlayers: 10,
    url: "https://www.jackboxgames.com/drawful-animate/",
    description:
      "It’s alive! The guessing game with terrible drawings and hilariously wrong answers makes a dynamic return. In this revamped title, players create looping, two-frame animations based on weird and random titles.",
    pack_url: "https://www.jackboxgames.com/party-pack-eight/",
    duration: "15-30 minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Job Job",
    pack: "The Jackbox Party Pack 8",
    image: "job_job.png",
    minPlayers: 3,
    maxPlayers: 10,
    url: "https://www.jackboxgames.com/job-job/",
    description:
      "Use other people’s words to create unique and funny answers to classic job interview questions. Go head to head to see who scores the job!",
    pack_url: "https://www.jackboxgames.com/party-pack-eight/",
    duration: "15-25 minutes",
    familyFriendlySetting: true,
    manualCensoring: false,
    extendedTimers: true,
  },
  {
    name: "The Poll Mine",
    pack: "The Jackbox Party Pack 8",
    image: "the_poll_mine.jpg",
    minPlayers: 2,
    maxPlayers: 10,
    url: "https://www.jackboxgames.com/the-poll-mine/",
    description:
      "A survey game that’s all about YOU! Split into teams and see who can escape from the witch’s lair! Players individually rank their choices to a difficult question, then must guess how the group answered as a whole. How well do you know your friends?!",
    pack_url: "https://www.jackboxgames.com/party-pack-eight/",
    duration: " ~15 minutes minutes",
    familyFriendlySetting: true,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Weapons Drawn",
    pack: "The Jackbox Party Pack 8",
    image: "weapons_drawn.jpg",
    minPlayers: 4,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/weapons-drawn/",
    description:
      "A social deduction game where everyone is both a murderer and a detective. Players doodle all the clues, hiding a letter from their name in the weapon drawings. Can you solve murders while trying to get away with your own?",
    pack_url: "https://www.jackboxgames.com/party-pack-eight/",
    duration: "20-40 minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: true,
  },
  {
    name: "The Wheel of Enormous Proportions",
    pack: "The Jackbox Party Pack 8",
    image: "the_wheel_of_enormous_proportions.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/the-wheel-of-enormous-proportions/",
    description:
      "Trivia has never been so large! A fantastic, mystical wheel challenges you with a variety of trivia prompts. Winners are awarded slices of the Wheel’s face with a chance to win big with each nail-biting spin. In the end, one player will have their most burning question answered by the great Wheel.",
    pack_url: "https://www.jackboxgames.com/party-pack-eight/",
    duration: "15-25 minutes",
    familyFriendlySetting: true,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Drawful 2",
    pack: "Standalone Title",
    image: "drawful_2.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://jackboxgames.com/drawful-two/",
    description:
      "Your phones or tablets are your controllers! The game of terrible drawings and hilariously wrong answers.",
    duration: "15-20 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "Fibbage",
    pack: "Standalone Title",
    minPlayers: 2,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/fibbage/",
    description:
      "Fibbage is the lying, bluffing, fib-till-you-win trivia party game from the makers of YOU DON’T KNOW JACK! Fool your friends with your lies, avoid theirs, and find the (usually outrageous) truth. And get this: your phone or tablet is your controller!",
    duration: "15-20 Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Quiplash",
    pack: "Standalone Title",
    image: "quiplash.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/quiplash/",
    description: "Quiplash is the gut-busting battle of wits and wittiness!",
    duration: "15 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
  {
    name: "You Don't Know Jack - Classic Bundle",
    pack: "Standalone Title",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/ydkj-classic-bundle/",
    description:
      "Since 1995, Jackbox Games (formerly Jellyvision) has been making YOU DON’T KNOW JACK, the hit comedy trivia series where high culture and pop culture collide. And we refuse to stop until every human being has played it.",
    duration: "25 Minutes",
    familyFriendlySetting: false,
    manualCensoring: false,
    extendedTimers: false,
  },
  {
    name: "Quiplash 2 InterLASHional",
    pack: "Standalone Title",
    image: "quiplash_2_interlashional.jpg",
    minPlayers: 3,
    maxPlayers: 8,
    url: "https://www.jackboxgames.com/quiplash-two-interlashional/",
    description:
      "The “say anything” party game is going international! All the hilarious content from Quiplash 2, now in French, Italian, German, and Spanish! With 100 NEW prompts in each language! (And you can still play in boring old English.) Get this QUINTILINGUAL Quiplash now, and take your next party global!",
    duration: "15 Minutes",
    familyFriendlySetting: true,
    manualCensoring: true,
    extendedTimers: true,
  },
].sort((a, b) => a.name.localeCompare(b.name));

export default games;
